### ISSUE TITLE
Jump to title

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/script.skin.helper.service#48]
@Nessus85100 

You requested to have something in the script to be able to quickly jump to a sortletter within a view.
This has just been added to the script.

Please grab the latest version from Git and test ;-)

README:
https://github.com/marcelveldt/script.skin.helper.service#jump-to-alphabet-list-for-media-views

**Comment by Nessus85100** [comment]
Works perfectly. The only thing that i can mention is that when a letter is not available still you can navigate on it. I know that since this is a panel container it's not possible to avoid it but i thought mention it if there is way to avoid it with some kind of python trick/hack. If not then you can close this.

Thanks for adding this

Cheers
Nessus

**Comment by marcelveldt** [comment]
Well, there is nothing I can do about that pythons-side as the listing provided by python has no link with the panel container in the skin but there is a small trick you can do inside the skin itself.

Just add a hidden button to your focusedlayout of the container used to display the alphabet:

```
<control type="button">
                        <visible>false</visible>
                        <onfocus condition="!IsEmpty(Container(6002).ListItem.Property(NotAvailable)) + Container(6002).OnNext">Control.Move(6002,1)</onfocus>
                        <onfocus condition="!IsEmpty(Container(6002).ListItem.Property(NotAvailable)) + Container(6002).OnPrevious">Control.Move(6002,-1)</onfocus>
                    </control>
```

Replace 6002 with the container ID of your panel and it should work
