### ISSUE TITLE
Window(Home).Property(SkinHelper.ListItem.Cast) empty

### ISSUE THREAD

**Issue by gade01** [marcelveldt/script.skin.helper.service#91]
Hi Marcel.

After the refactor of this script (some time ago), Window(Home).Property(SkinHelper.ListItem.Cast) hasn't returned any value.

I have just looked into it, and both
`plugin://script.skin.helper.service/?action=getcast&amp;movieset=$INFO[ListItem.DBID]`
`plugin://script.skin.helper.service/?action=getcast&amp;movie=$INFO[ListItem.DBID]`
works.

I have placed a container outside of the window with the above content and use this textbox:

`<control type="textbox" id="8500">`
`	<description>Cast</description>`
`	<left>30</left>`
`	<top>500</top>`
`	<width>177</width>`
`	<height>134</height>`
`	<aligny>top</aligny>`
`	<font>MediaInfoFont2</font>`
`	<textcolor>MediaInfoItemColor2</textcolor>`
`	<shadowcolor>ShadowColor</shadowcolor>`
`	<include>WrapInfoViewCatLabel</include>`
`	<label>$INFO[Window(Home).Property(SkinHelper.ListItem.Cast)]</label>`
`	<autoscroll time="2000" delay="5900" repeat="10000">true</autoscroll>`
`	<visible>!String.IsEmpty(Window(Home).Property(SkinHelper.ListItem.Cast))</visible>`
</control>`

**Comment by marcelveldt** [comment]
Hmmm, what are you looking for ? A list of all cast members as Window property ?
I'm not sure if that was ever in the code but I can add it in but why not use the normal $INFO[ListItem.Cast] ?

Maybe you better use the plugin entries in combination with a container ?
That way you can show the cast members the way you want. With images, or just text etc.
So, instead of a textbox, use a container with the plugin://script.skin.helper.service/?action=getcast as path

**Comment by gade01** [comment]
Exactly, I'm looking for a window property for cast members as described here: https://github.com/marcelveldt/script.skin.helper.service/wiki/Cast-details

It used to work before the refactor of the script, if a container with the content plugin://script.skin.helper.service/?action=getcast was provided.

But it's no bother, I can use the container instead. 
I just didn't want the content to be able to be focused.
